name: build-check

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Check Streamlit app builds
        run: |
          timeout 30s streamlit run app.py --server.headless true || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi